### ISSUE TITLE
bad attachements with special character (ä ö ü) release not possible

### ISSUE THREAD

**Issue by Schroeffu** [mailwatch/1.2.0#1109] opened 2018-10-01 07:25 UTC
### Issue summary
Bad Attachements which are going to quarantine, with special characters in their file name, are saved on Linux with a very strange filename. Releasing of this files in Mailwatch is not possible, MailWatch sais file not found.

Filename Attachement
-  "1KKüchen.cer"
is saved in the linux filesystem under /var/spool/MailScanner/quarantine/* like this:
- '1K'$'\201''chen.cer'

MailWatch WebUI sais:

1K�chen.cer | cannot open `/var/spool/MailScanner/quarantine/20181001/374D53C0992.AC940/1Kchen.cer' (No such file or directory) | 20181001/374D53C0992.AC940/1K�chen.cer
-- | -- | --

### Steps to reproduce
1.  Send yourself an eMail with bad ending, for example .cer , with character ü inside. /EDIT: the character which generated this issue is not found yet, a simple "ü" is not enough :') See comments below
2. Try to release the mail.. not working.

### Expected result
EMail should be released.

### Actual result
eMail stuck in quarantine

### Version and method
 - MailWatch Version: 1.2.10 stable
 - Install type: Zip
 - Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
 - Operation System: Ubuntu 
 - PHP version: 7.2.7-0ubuntu0.18.04.2
 - Database: mariadb
 - Mail Server: Postfix
 - Used web server: Apache

### Client configuration 
 - Operation System: Windows 
 - Browser: Chrome

**Comment by Schroeffu** [comment] 2018-10-01 07:35
Workaround: Rename the files on the filesystem, release afterwards:

- mv '1K'$'\201''chenl.cer' 1Kuechen.cer
- release in WebUI, should work now.

**Comment by Skywalker-11** [comment] 2018-10-01 23:14
What settings do you have set for the following MailScanner config settings?
`Quarantine Whole Message`
`Quarantine Whole Messages As Queue Files`

**Comment by ghost** [comment] 2018-10-04 00:35
I am having trouble reproducing this so far, but the filename does get uglified when I insert a special character....

**Comment by ghost** [comment] 2018-10-04 00:40
I am getting a different behavior, and I am able to release.  The filename is getting changed, but it is able to be released:

![image](https://user-images.githubusercontent.com/6255179/46446831-848bda80-c74c-11e8-8b42-f5df35e33932.png)

**Comment by Schroeffu** [comment] 2018-10-04 06:57
@Skywalker-11 my settings are:

MailScanner.conf:Quarantine Whole Message = yes
MailScanner.conf:Quarantine Whole Messages As Queue Files = no

@shawniverson yes, I also tried to reproduce today, and a default "ü" really ends up like you detected, corrupt filename but release-able.

The original mail I opened this bugreport seems to have something different. The info-mail from mailscanner about this detection also includes a question mark. I don't see the difference. unfortunately I cannot reprocue that by myself, it is a mail with license files send by a bot (or somehow automated) from a supplier.

screenshot: https://imgur.com/a/Hh29zFO (original issue)
screenshot: https://imgur.com/a/ackmD06 (my try to reproduce with "Küchen.cer")

My workaround was: rename the files on the filesystem, for example:

`mv '2K'$'\201''chen.cer' 2Kuechen.cer`

Then I could release them with the new filename.

**Comment by Schroeffu** [comment] 2018-10-04 07:09
I tried to reproduce with other special characters, like Chinese figure 象 (ChromeSetup象.exe), but MailWatch is not blocking that .exe/.cer ending anymore with 象 in filename. Seems to be another bug but for MailScanner

**Comment by ghost** [comment] 2018-10-13 23:51
MailWatch team:

FYI...this is a really bad bug.

https://github.com/MailScanner/v5/issues/233

I am hitting a brick wall.  The problem is in the MIME::Parser perl module, and so far, I have not found a fix yet or an alternative solution.

**Comment by ghost** [comment] 2018-10-13 23:58
I can stop gap the problem somewhat by setting decode_headers to 1, but it is a nasty bandaid.  It may be our only option at the moment, so it is better than nothing.  At least it will catch most encoded UTF8 MIME attachments.  I have submitted a bug report to MIME::Tools, but based on the recent activity, I wouldn't hold my breath.

**Comment by shawniverson** [comment] 2018-12-09 16:49
Possible permanent fix:

https://github.com/MailScanner/v5/pull/329

**Comment by ghost** [comment] 2018-12-10 20:08
This issue should be resolved in the soon to be released MailScanner 5.0.3-1.  The key is to make sure you are using MIME::Tools version 5.509 (latest).  I observed this issue on version 5.505, but I cannot reproduce on 5.509.  The MailScanner installers are set to prefer cpan over repos for MIME::Tools since commit https://github.com/MailScanner/v5/commit/481eed103674c0afcf3c4622f8fe6b883c975b8e because many distros still have the bad version as a package.

**Comment by Skywalker-11** [comment] 2018-12-11 20:06
Do you know if 5.508 (current version in Debian 9) is also affected?

**Comment by ghost** [comment] 2018-12-11 20:22
@Skywalker-11 I can test that and find out while I'm running the debian testing.

**Comment by ghost** [comment] 2018-12-18 10:18
@Skywalker-11 5.508 appears to be ok.

**Closed as completed** 2018-12-18 15:25 UTC
Labels: bug, MailScanner-Issue
