### ISSUE TITLE
Mailscanner not logging to SQL

### ISSUE THREAD

**Issue by mbotebm** [mailwatch/1.2.0#1240] opened 2021-12-15 08:07 UTC
### Issue summary
I have installed mailwatch on a Centos System with the specifications below. I have tried everything but there are no messages been logged to SQL. MailScanner --lint show no errors at all. I have also edited the database properties in files in this directory. /usr/share/MailScanner/perl/custom 

Emails get scanned and delivered. Only issue is logging to maillog table. The in and out queue logs okay. Please assist

### Steps to reproduce
1. Checked all MailScanner.conf settings
2. Confirmed I can log in to the web interface
3. Checked all database configs
4. Confirmed I am able to login to the database using the parameters I have entered.

### Expected result
I expect to see such a message indicating the mail has been logged to SQL
Dec 15 10:46:41 mail MailScanner[2185]: Logging message 1mxOze-0002tf-O5 to SQL

### Actual result
Mail is delivered but no logging happens
Dec 11 18:00:09 lauser MailScanner[19256]: Uninfected: Delivered 1 messages
Dec 11 18:00:09 lauser MailScanner[19256]: Deleted 1 messages from processing-database

### Version and method
 - MailWatch Version: MailWatch for MailScanner v1.2.18 -
 - Install type: tarball
 - Updated from an older MailWatch or fresh install: Fresh install 

### Server configuration
 - Operation System: CentOS Linux release 7.9.2009 (Core)
 - PHP version: php-5.4.16-48.el7.x86_64
 - Database: MariaDB-5.5.68
 - Mail Server: exim
 - Used web server: Apache httpd-2.4.6

### Client configuration 
 - Operation System: Windows 10
 - Browser: Chrome

**Comment by Fonant** [comment] 2021-12-15 10:04
Check the database logs? Might be to do with 4-byte UTF-8 characters not being compatible with the schema, so MariaDB fails to execute the "INSERT" query. Check that you've run the MailWatch database schema upgrade script, too.

**Comment by mbotebm** [comment] 2021-12-15 10:49
- Cleanup orphaned user_filters...................................... OK
 - Add id field and primary key to `audit_log` table..................
ALREADY DONE
 - Add inq_id field and primary key to `inq` table....................
ALREADY DONE
 - Add maillog_id field and primary key to `maillog` table............
ALREADY DONE
 - Add rblspamreport field to `maillog` table.........................
ALREADY DONE
 - Add token field to `maillog` table.................................
ALREADY DONE
 - Add released field to `maillog` table..............................
ALREADY DONE
 - Add last_update field to `maillog` table...........................
ALREADY EXIST
 - Add salearn field to `maillog` table...............................
ALREADY DONE
 - Add messageid field to `maillog` table.............................
ALREADY DONE
 - Check for missing tokens in `maillog` table........................
NOTHING FOUND
 - Add mtalog_id field and primary key to `mtalog` table..............
ALREADY DONE
 - Add mtalog_id field and primary key to `outq` table................
ALREADY DONE
 - Add id field and primary key to `saved_filters` table..............
ALREADY DONE
 - Add mtalog_id field and primary key to `user_filters` table........
ALREADY DONE

 - Dropping too big index `maillog_from_idx` on table `maillog`.......
ALREADY DONE
 - Dropping too big index `maillog_to_idx` on table `maillog`.........
ALREADY DONE

 - Convert database to utf8mb4........................................
ALREADY DONE

 - Convert table `audit_log` to utf8mb4...............................
ALREADY CONVERTED
 - Convert table `autorelease` to utf8mb4.............................
ALREADY CONVERTED
 - Convert table `blacklist` to utf8mb4...............................
ALREADY CONVERTED
 - Convert table `inq` to utf8mb4.....................................
ALREADY CONVERTED
 - Convert table `maillog` to utf8mb4.................................
ALREADY CONVERTED



 - Convert table `mcp_rules` to utf8mb4............................... ERROR
Database error: Specified key was too long; max key length is 767 bytes -
SQL = 'ALTER TABLE `mcp_rules` CONVERT TO CHARACTER SET utf8mb4 COLLATE
utf8mb4_unicode_ci'
***@***.*** ~]#

I have just noticed the error on upgrade. Let me check what could be the
problem and get back to you.

Regards,
Boniface

**Comment by Skywalker-11** [comment] 2021-12-15 10:58
Please try the updated upgrade.php from [https://github.com/mailwatch/MailWatch/blob/1.2/upgrade.php](https://github.com/mailwatch/MailWatch/blob/1.2/upgrade.php) it should contain a fix for that issue

**Comment by Skywalker-11** [comment] 2021-12-15 20:37
Another issue might be  that your MariaDB server is too old. You should use MySQL > 5.6  or MariadDB > 10.x

**Comment by mbotebm** [comment] 2021-12-16 09:42
I upgraded to 10.1.48-MariaDB, reinstalled the mailscanner but still the messages are not being logged. I can view the queue cont quite okay. Not sure where I am going wrong.

I have also run the upgrade script successfully 

ec 16 12:33:03 lauser MailScanner[3521]: New Batch: Scanning 1 messages, 1186 bytes
Dec 16 12:33:03 lauser MailScanner[3521]: Virus and Content Scanning: Starting
Dec 16 12:33:03 lauser MailScanner[3521]: Uninfected: Delivered 1 messages
Dec 16 12:33:03 lauser MailScanner[3521]: Deleted 1 messages from processing-database
Dec 16 12:33:03 lauser MailScanner[4652]: MailScanner Email Processor version 5.4.3 starting...
Dec 16 12:33:03 lauser MailScanner[4652]: Reading configuration file /etc/MailScanner/MailScanner.conf
Dec 16 12:33:03 lauser MailScanner[4652]: Reading configuration file /etc/MailScanner/conf.d/README
Dec 16 12:33:03 lauser MailScanner[4652]: Read 1500 hostnames from the phishing whitelist
Dec 16 12:33:03 lauser MailScanner[4652]: Read 4790 hostnames from the phishing blacklists
Dec 16 12:33:03 lauser MailScanner[4652]: Config: calling custom init function MailWatchLogging
Dec 16 12:33:03 lauser MailScanner[4652]: Using SpamAssassin results cache
Dec 16 12:33:03 lauser MailScanner[4652]: Connected to SpamAssassin cache database
Dec 16 12:33:03 lauser MailScanner[4652]: Expired 2 records from the SpamAssassin cache
Dec 16 12:33:03 lauser MailScanner[4652]: Enabling SpamAssassin auto-whitelist functionality...
Dec 16 12:33:04 lauser MailScanner[4652]: Connected to Processing Attempts Database
Dec 16 12:33:04 lauser MailScanner[4652]: Found 1061 messages in the Processing Attempts Database
Dec 16 12:33:04 lauser MailScanner[4652]: Using locktype = posix

**Comment by mbotebm** [comment] 2021-12-17 07:32
What I have done so far

Reinstalled MailScanner and setup all configs
Reinstalled clamav antivirus
Backed up my database and uninstalled Mariadb
Upgraded the database from Mariadb-5.5 to Mariadb-10.1 and restored the databases.
Confirmed I can log in to the mailwatch web interface and other instances requiring the databases.
Checked all database configs in /usr/share/MailScanner/perl/custom directory and confirmed they are all fine.

**Result**
I can deliver emails correctly but still no logging to SQL as per the above log.

**Comment by Skywalker-11** [comment] 2021-12-17 10:06
Can you post the output of `MailScanner --lint`

**Comment by mbotebm** [comment] 2021-12-17 10:33
[root@mail tmp]# MailScanner --lint
Trying to setlogsock(unix)

Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 1500 hostnames from the phishing whitelist
Read 4836 hostnames from the phishing blacklists
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child

Checking version numbers...
Version number in MailScanner.conf (5.4.3) is correct.

Your envelope_sender_header in spamassassin.conf is correct.
MailScanner setting GID to  (93)
MailScanner setting UID to  (93)

Checking for SpamAssassin errors (if you use it)...
Using SpamAssassin results cache
Connected to SpamAssassin cache database
SpamAssassin reported no errors.
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There is 1 message in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = clamd"
Found these virus scanners installed: clamd
===========================================================================
Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
Clamd::INFECTED::Win.Test.EICAR_HDB-1 :: ./1/
Clamd::INFECTED:: Win.Test.EICAR_HDB-1 :: ./1/eicar.com
Virus Scanning: Clamd found 2 infections
Infected message 1 came from 10.1.1.1
Virus Scanning: Found 2 viruses
===========================================================================
Virus Scanner test reports:
Clamd said "eicar.com was infected: Win.Test.EICAR_HDB-1"

If any of your virus scanners (clamd)
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
Config: calling custom end function MailWatchLogging
[root@mail tmp]#

**Comment by ghost** [comment] 2021-12-17 17:23
Can you do a ```ps -ef | grep MailWatch``` to confirm that the MailWatch Logging child is in fact alive?

**Comment by mbotebm** [comment] 2021-12-21 07:45
[root@mail ~]# ps -ef | grep MailWatch

root      6650  6413  0 10:44 pts/0    00:00:00 grep --color=auto MailWatch

**Comment by ghost** [comment] 2021-12-21 16:09
Hi @mbotebm, so what you should see is a "MailWatch SQL," which means that something is wrong.  Either the credentials in /usr/share/MailScanner/perl/custom/MailWatchConf.pm are wrong, or we have something else preventing the process from spawning

**Comment by mbotebm** [comment] 2021-12-22 06:21
The credentials are correct. Must be something else. If its a misconfiguration, seems like I am repeating it again since i reinstalled the Mailwatch and Mailscanner before. Maybe it could be a missing perl module?

**Comment by ghost** [comment] 2021-12-22 14:15
I don't think so, based on your MailScanner --lint, we see the following:

```
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child
```

That indicates the perl modules are okay.  There is something we can't see, due to syslog bug with #1230, we probably can't see the cause of the actual failure when it first tries to spawn and connect to the database.

We need to do some debugging, so I think I'm going to tackle issue #1230 and see if we can get this to start logging information we can see.

**Comment by mbotebm** [comment] 2021-12-23 06:11
Thanks. Am a bit lost on what to do at the moment. However I am still
digging around.Hopefully wont mess it further.

**Comment by ghost** [comment] 2021-12-30 17:23
@mbotebm I have the logging (to syslog) portion resolved I believe in this PR https://github.com/mailwatch/MailWatch/pull/1243
Please update your MailWatch.pm using this PR and post what your results from the mail log. Hopefully this will shed some light on the issue here of logging to SQL.

**Comment by mbotebm** [comment] 2021-12-30 17:42
Thanks. I will definitely update you

**Comment by mbotebm** [comment] 2022-01-02 08:42
I have just tested the updated and seems I have no luck in getting the
MailWatch Logging Child to run. When I check running processes I still have
no MailWatch SQL.

There are still no errors on MailScanner --lint

**Comment by ghost** [comment] 2022-01-02 23:04
@mbotebm I have a test I want you to run. Please place this in a file such as test.pl, chmod +x test.pl, and see if the bind is successful. If successful it will just return to the prompt without any output.

```
#!/usr/bin/perl

use strict;
use Socket;

my $loop = inet_aton("127.0.0.1");
my $server_port = 11553;

socket(SERVER, PF_INET, SOCK_STREAM, getprotobyname("tcp"));
setsockopt(SERVER, SOL_SOCKET, SO_REUSEADDR, 1);
my $addr = sockaddr_in($server_port, $loop);
bind(SERVER, $addr) or print "Unable to bind to port\n";
listen(SERVER, SOMAXCONN) or print "Unable to listen on port\n";
close(SERVER);
```

**Comment by mbotebm** [comment] 2022-01-03 05:09
The file runs succesfully without an error.

**Comment by ghost** [comment] 2022-01-03 12:39
@mbotebm We can rule out the part of the code that exits silently. When you start MailScanner, do you get anything in /var/log/maillog coming from MailWatch SQL? At a minimum you should see a single "Started MailWatch SQL Logging child" somewhere near the start of the first MailScanner child. I moved this log attempt past the initialization phase, so it will be interesting to know if you still see it or not.

**Comment by mbotebm** [comment] 2022-01-03 13:02
No.This does not happen.  See below output of maillog

Jan  3 16:00:38 lauser MailScanner[26512]: MailScanner Email Processor
version 5.4.3 starting...
Jan  3 16:00:38 lauser MailScanner[26512]: Reading configuration file
/etc/MailScanner/MailScanner.conf
Jan  3 16:00:38 lauser MailScanner[26512]: Reading configuration file
/etc/MailScanner/conf.d/README
Jan  3 16:00:38 lauser MailScanner[26512]: Read 1500 hostnames from the
phishing whitelist
Jan  3 16:00:38 lauser MailScanner[26512]: Read 3801 hostnames from the
phishing blacklists
Jan  3 16:00:38 lauser MailScanner[26512]: Config: calling custom init
function MailWatchLogging
Jan  3 16:00:38 lauser MailScanner[26512]: Using SpamAssassin results cache
Jan  3 16:00:38 lauser MailScanner[26512]: Connected to SpamAssassin cache
database
Jan  3 16:00:38 lauser MailScanner[26512]: Enabling SpamAssassin
auto-whitelist functionality...
Jan  3 16:00:39 lauser MailScanner[26512]: Connected to Processing Attempts
Database
Jan  3 16:00:39 lauser MailScanner[26512]: Found 0 messages in the
Processing Attempts Database
Jan  3 16:00:39 lauser MailScanner[26512]: Using locktype = posix

**Comment by ghost** [comment] 2022-01-04 02:36
@mbotebm I would like to spin up an environment and walk through your steps to see if I can reproduce this.  I appreciate you continuing to try to get this resolved.  What is perplexing is that the rest of initialization and operation should place messages in the maillog indicating a failure. But that is not happening and we ruled out any issues with binding and listening on the port.

Also, there are a couple of lines in MailWatch.pm you can uncomment near the beginning to enable db trace logging. I wonder if anything would be logged to the trace log that could provide a clue?

**Comment by ghost** [comment] 2022-01-04 03:51
@mbotebm Quick question, after you upgraded MariaDB and restored the database, did you execute upgrade.php again afterward?

**Comment by mbotebm** [comment] 2022-01-04 04:07
Yes I did upgrade it. I also have the dbitrace uncommented though I have no
errors or logs

**Comment by ghost** [comment] 2022-01-05 13:32
Still working on trying to reproduce this issue.

**Comment by ghost** [comment] 2022-01-09 18:32
I have concluded my testing as follows. I cannot reproduce this issue.  One notable difference is that I used MariaDB 10.2 from the IUS repo. I'm not sure where you obtained version 10.1 @mbotebm but might be worthwhile to try 10.2 instead.

MailWatch for MailScanner v1.2.18 with modifications in PR #1243 
CentOS Linux release 7.9.2009 (Core)
PHP version: php-5.4.16-48.el7.x86_64
Initial Database: MariaDB-5.5.68 (deliberated started on this version to simulate same failures)
Upgraded Database: mariadb102-server-10.2.30-1.el7.ius.x86_64
Mail Server: exim
Used web server: Apache httpd-2.4.6

```
Jan  9 13:25:32 localhost MailScanner[14695]: New Batch: Scanning 1 messages, 1342 bytes
Jan  9 13:25:32 localhost MailScanner[14695]: Virus and Content Scanning: Starting
Jan  9 13:25:32 localhost MailScanner[14695]: Uninfected: Delivered 1 messages
Jan  9 13:25:32 localhost MailScanner[14695]: Deleted 1 messages from processing-database
Jan  9 13:25:32 localhost MailScanner[14695]: MailWatch: Logging message 1m4VA2-0003p4-Pf to SQL
Jan  9 13:25:32 localhost journal: MailWatch SQL[14665]: 1m4VA2-0003p4-Pf: Logged to MailWatch SQL
```

**Comment by mbotebm** [comment] 2022-02-08 06:11
Just an update.

I created a new instance on the same platform (Centos 7, MariaDB, PHP) with
no success. Tried the same with community version of Mysql and still
couldnt get messages logging.

Yesterday, I decided to try out using Fedora using the default Mariadb
Database and version. Surprisingly I did not have much problems having the
message count showing. Only thing left is to check out why there are no
rows being returned in the table hence the empty recent messages page.

See attached screenshot
[image: image.png]
My test Environment
Fedora release 24
mariadb-server-10.0.28
PHP 5.6.29


MailScanner -lint
Trying to setlogsock(unix)

Reading configuration file /etc/MailScanner/MailScanner.conf
Reading configuration file /etc/MailScanner/conf.d/README
Read 1500 hostnames from the phishing whitelist
Read 3293 hostnames from the phishing blacklists
Config: calling custom init function MailWatchLogging
MailWatch: Started MailWatch SQL Logging child

Checking version numbers...
Version number in MailScanner.conf (5.4.3) is correct.

Your envelope_sender_header in spamassassin.conf is correct.
MailScanner setting GID to  (93)
MailScanner setting UID to  (93)

Checking for SpamAssassin errors (if you use it)...
Using SpamAssassin results cache
Connected to SpamAssassin cache database
SpamAssassin reported no errors.
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
There are 0 messages in the Processing Attempts Database
Using locktype = posix
MailScanner.conf says "Virus Scanners = clamd"
Found these virus scanners installed:
===========================================================================
Filename Checks: Windows/DOS Executable (1 eicar.com)
Other Checks: Found 1 problems
Virus and Content Scanning: Starting
===========================================================================

If any of your virus scanners ()
are not listed there, you should check that they are installed correctly
and that MailScanner is finding them correctly via its virus.scanners.conf.
Config: calling custom end function MailWatchLogging


MailScanner Logs
Feb  8 06:09:18 mailout MailScanner[27233]: MailWatch: Started MailWatch
SQL Logging child
Feb  8 06:09:23 mailout MailScanner[27233]: MailWatch: Logging message
1nHJgh-0007PI-PC to SQL
Feb  8 06:09:23 mailout MailScanner[28518]: MailWatch: 1nHJgh-0007PI-PC:
Logged to MailWatch SQL
Feb  8 06:09:29 mailout MailScanner[27233]: New Batch: Scanning 1 messages,
36360 bytes
Feb  8 06:09:29 mailout MailScanner[27233]: Virus and Content Scanning:
Starting
Feb  8 06:09:30 mailout MailScanner[27233]: Uninfected: Delivered 1 messages
Feb  8 06:09:30 mailout MailScanner[27233]: Deleted 1 messages from
processing-database
Feb  8 06:09:30 mailout MailScanner[27233]: MailWatch: Logging message
1nHJgt-0007Q8-UL to SQL
Feb  8 06:09:30 mailout MailScanner[28518]: MailWatch: 1nHJgt-0007Q8-UL:
Logged to MailWatch SQL

**Comment by mbotebm** [comment] 2022-02-08 07:06
Managed to sort out the mails not showing up. It was an issue with
Mailwatch home on conf.php which is now sorted.

**Closed as completed** 2022-02-19 20:44 UTC
Labels: bug
